language: go

go:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - tip

matrix:
  allow_failures:
    - go: tip

install: go get .

script: test -n "$(go tool | grep '^cover$')" && go test -v -cover || go test -v
